# Generated by Django 4.2 on 2023-06-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0005_artists_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_app.albums'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='audio_file',
            field=models.FileField(upload_to='static/audio_files/'),
        ),
    ]
