# Generated by Django 4.2 on 2023-06-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0006_alter_tracks_album_alter_tracks_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_app.albums'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='static/audio_files/'),
        ),
    ]
